package Sprint2;


import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author taruc
 */
public class ChooseRes extends javax.swing.JFrame {

    List<Restaurant> list = new ArrayList<Restaurant>();
     List<place> western = new ArrayList<place>();
    List<place> noodle = new ArrayList<place>();
    List<place> rice = new ArrayList<place>();
    
    public ChooseRes() {
        Restaurant western = new Restaurant("Setapak","Western");
        Restaurant noodle = new Restaurant("Wangsa Maju","Noodle");
        Restaurant rice = new Restaurant("Wangsa Walk","Rice");
        
        list.add(western);
        list.add(noodle);
        list.add(rice);
        initComponents();
    }
    
    public String[] toArray(){
        String[] items = new String[list.size()];
        for(int i=0;i<list.size();i++){
            items[i] = list.get(i).getResName();
        }
        return items;
    }
    
    public void westernList(){
        western.clear();
        place w1 = new place("Setapak","HI cafe");
        place w2 = new place("Wangsa Maju","You cafe");
        place w3 = new place("Wangsa Maju","We cafe");
        place w4 = new place("Wangsa Walk","They cafe");
        western.add(w1);
        western.add(w2);
        western.add(w3);
        western.add(w4);
    }
     public void noodleList(){
         western.clear();
        place n1 = new place("Setapak","HI cafe");
        place n2 = new place("Setapak","Boom cafe");
        place n3 = new place("Wangsa Maju","Hey cafe");
        place n4 = new place("Wangsa Maju","Only cafe");
        western.add(n1);
        western.add(n2);
        western.add(n3);
        western.add(n4);
    }
      public void riceList(){
        western.clear();
        place r1 = new place("Wangsa Maju","P cafe");
        place r2 = new place("Wangsa Maju","Q cafe");
        place r3 = new place("Wangsa Walk","R cafe");
        place r4 = new place("Wangsa Walk","S cafe");
        western.add(r1);
        western.add(r2);
        western.add(r3);
        western.add(r4);
    }
        public void addRowToJTable(){
            
        String value = (String)ddlRestaurant.getSelectedItem();
        
        if(value.equals("Western")){
            westernList();
        }else if(value.equals("Noodle")){
            noodleList();
        }else if(value.equals("Rice")){
            riceList();
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object rowData[] = new Object[western.size()];
        
        model.setRowCount(0);
        for(int i = 0; i < western.size(); i++)
        {
            rowData[0] = western.get(i).getPlace();
            rowData[1] = western.get(i).getShopName();
            
            model.addRow(rowData);
        }
        
}
       
       
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddlRestaurant = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Restaurant Category");

        jLabel2.setText("Option :");

        ddlRestaurant.setModel(new javax.swing.DefaultComboBoxModel<String>(toArray())
        );
        ddlRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlRestaurantActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place", "Shop Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ddlRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddlRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlRestaurantActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ddlRestaurantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //String value = (String)ddlRestaurant.getSelectedItem();
        
         addRowToJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ddlRestaurant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
