/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignments;

import assignments.Order;
import java.awt.Color;
import javax.swing.JOptionPane;
   
/**
 *
 * @author User
 */
public class CalculatePetrol extends javax.swing.JFrame {
    private double price1,price2,price3,distance1,distance2,distance3;
    private int time1,time2,time3;
    private String output1, output2,output3,output4, output5,output6,output7, output8,output9,Des; 
    
    /**
     * Creates new form NewJFrame
     */
    public CalculatePetrol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        delivery1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        delivery1b = new javax.swing.JTextField();
        delivery1c = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        delivery2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        delivery2b = new javax.swing.JTextField();
        delivery2c = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        delivery3 = new javax.swing.JTextField();
        delivery3b = new javax.swing.JTextField();
        delivery3c = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        petrol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Calculate Petrol Price");

        jLabel5.setText("Choose Destination:");

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wangsa Maju", "Genting Klang", "Taman Bunga Raya(TBR)", "Platinum Victory(PV)" }));
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delivery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delivery1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Delivery Man1(Wangsa) ----->Distance(KM):");

        jLabel3.setText("Petrol(RM):");

        jLabel6.setText("Time(Minutes):");

        jLabel2.setText("Delivery Man2(Genting Klang) ----->Distance(KM):");

        jLabel7.setText("Petrol(RM):");

        jLabel8.setText("Time(Minutes):");

        jLabel9.setText("Delivery Man3(Taman Bunga Raya) ----->Distance(KM):");

        jLabel10.setText("Petrol(RM):");

        jLabel11.setText("Time(Minutes):");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Current Petrol Price(RM):");

        petrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petrolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addGap(98, 98, 98)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delivery1)
                            .addComponent(delivery1b)
                            .addComponent(delivery1c)
                            .addComponent(delivery2)
                            .addComponent(delivery2c)
                            .addComponent(delivery2b)
                            .addComponent(delivery3)
                            .addComponent(delivery3b)
                            .addComponent(delivery3c, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(petrol))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(petrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delivery1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(delivery1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(delivery1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delivery2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delivery2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delivery2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delivery3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(delivery3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(delivery3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_destinationActionPerformed


    
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        Des =destination.getSelectedItem().toString();
         try {
         Double.parseDouble(petrol.getText());
  
      } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(null,"Please enter only number!",null,JOptionPane.ERROR_MESSAGE);
      }//error message if enter letter
         double Petrol = Double.parseDouble(petrol.getText());

        if(Des.equals("Wangsa Maju"))
        {
            distance1=1;//wangsa to wangsa
            price1=(distance1/10)* Petrol;
            time1=35;
            distance2=5;//gk to wangsa
            price2=(distance2/10)* Petrol;
            time2=50;
            distance3=2.5;//tbr to wangsa
            price3=(distance3/10)*Petrol;
            time3=40;

        }
        else if(Des.equals("Genting Klang"))
        {
            distance1=5;//wangsa to gk
            price1=(distance1/10)* Petrol;
            time1=50;
            distance2=1;//gk to gk
            price2=(distance2/10)* Petrol;
            time2=35;
            distance3=3.7;//tbr to gk
            price3=(distance3/10)* Petrol;
            time3=40;

        }
        else if(Des.equals("Taman Bunga Raya(TBR)"))
        {
            distance1=2.5;//wangsa to tbr
            price1=(distance1/10)* Petrol;
            time1=40;
            distance2=3.7;//gk to tbr
            price2=(distance2/10)* Petrol;
            time2=40;
            distance3=1;//tbr to tbr
            price3=(distance3/10)* Petrol;
            time3=35;

        }
        else if(Des.equals("Platinum Victory(PV)"))
        {
            distance1=4.5;//wangsa to pv
            price1=(distance1/10)* Petrol;
            time1=45;
            distance2=2;//gk to pv
            price2=(distance2/10)* Petrol;
            time2=40;
            distance3=3;//tbr to pv
            price3=(distance3/10)* Petrol;
            time3=40;
        }
        output1=""+distance1;
        output2=""+price1;
        output3=""+time1;
        output4=""+distance2;
        output5=""+price2;
        output6=""+time2;
        output7=""+distance3;
        output8=""+price3;
        output9=""+time3;
        String result1 = String.format("%.2f", price1);
        String result2 = String.format("%.2f", price2);
        String result3 = String.format("%.2f", price3);
        delivery1.setText(output1);
        delivery1b.setText(result1);
        delivery1c.setText(output3);
        delivery2.setText(output4);
        delivery2b.setText(result2);
        delivery2c.setText(output6);
        delivery3.setText(output7);
        delivery3b.setText(result3);
        delivery3c.setText(output9);
        Biggest();
        Lowest();
        Medium();
    }//GEN-LAST:event_jButton1ActionPerformed
private void Biggest(){
    if (price1>price2)
    {
        if(price1>price3)
        {
            delivery1.setForeground(Color.red);
            delivery1b.setForeground(Color.red);
            delivery1c.setForeground(Color.red);//max=price1;
        }
        else if(price3>price1)
        {
            delivery3.setForeground(Color.red);
            delivery3b.setForeground(Color.red);
            delivery3c.setForeground(Color.red);//max=price3;
        }
    }
    else if(price2>price3)
    {
        if(price2>price1)
        {
            delivery2.setForeground(Color.red);
            delivery2b.setForeground(Color.red);
            delivery2c.setForeground(Color.red);//max=price2;
        }
        else if(price1>price2)
        {
            delivery1.setForeground(Color.red);
            delivery1b.setForeground(Color.red);
            delivery1c.setForeground(Color.red);//max=price1;
        }
    }
    else if(price3>price1)
    {
        if(price3>price2)
        {
             delivery3.setForeground(Color.red);
            delivery3b.setForeground(Color.red);
            delivery3c.setForeground(Color.red);//max=price3;
        }
        else if(price2>price3)
        {
           delivery2.setForeground(Color.red);
            delivery2b.setForeground(Color.red);
            delivery2c.setForeground(Color.red);//max=price2
        }
    }
}
    
private void Lowest(){
    if(price1<price2)
    {
        if(price1<price3)
        {
            delivery1.setForeground(Color.green);
            delivery1b.setForeground(Color.green);
            delivery1c.setForeground(Color.green);//min=price1;
        }
        else if(price3<price1)
        {
            delivery3.setForeground(Color.green);
            delivery3b.setForeground(Color.green);
            delivery3c.setForeground(Color.green);//min=price3;
        }
    }
    if(price2<price3)
    {
        if(price2<price1)
        {
            delivery2.setForeground(Color.green);
            delivery2b.setForeground(Color.green);
            delivery2c.setForeground(Color.green);//min=price2;
        }
        else if(price1<price2)
        {
            delivery1.setForeground(Color.green);
            delivery1b.setForeground(Color.green);
            delivery1c.setForeground(Color.green);//min=price1;
        }
    }
    if(price3<price1)
    {
        if(price3<price2)
        {
            delivery3.setForeground(Color.green);
            delivery3b.setForeground(Color.green);
            delivery3c.setForeground(Color.green);//min=price3;
        }
        else if(price2<price3)
        {
            delivery2.setForeground(Color.green);
            delivery2b.setForeground(Color.green);
            delivery2c.setForeground(Color.green);//min=price2;
        }
    }
}

private void Medium(){
    if(price1>price2&&price1>price3)
    {
        if(price3>price2)
        {
            delivery3.setForeground(Color.black);
            delivery3b.setForeground(Color.black);
            delivery3c.setForeground(Color.black);//med=price3;
        }
        else if(price2>price3)
        {
            delivery2.setForeground(Color.black);
            delivery2b.setForeground(Color.black);
            delivery2c.setForeground(Color.black);//med=price2;
        }
    }
    else if(price2>price1&&price2>price3)
    {
        if(price1>price3)
        {
            delivery1.setForeground(Color.black);
            delivery1b.setForeground(Color.black);
            delivery1c.setForeground(Color.black);//med=price1;
        }
        else if(price3>price1)
        {
            delivery3.setForeground(Color.black);
            delivery3b.setForeground(Color.black);
            delivery3c.setForeground(Color.black);//med=price3;
        }
    }
    else if(price3>price1&&price3>price2)
    {
        if(price1>price2)
        {
            delivery1.setForeground(Color.black);
            delivery1b.setForeground(Color.black);
            delivery1c.setForeground(Color.black);//med=price1;
        }
        else if(price2>price1)
        {
            delivery2.setForeground(Color.black);
            delivery2b.setForeground(Color.black);
            delivery2c.setForeground(Color.black);//med=price2;
        }
    }
}
    private void delivery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delivery1ActionPerformed
        
    }//GEN-LAST:event_delivery1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delivery1.setText("");
        delivery1b.setText("");
        delivery1c.setText("");
        delivery2.setText("");
        delivery2b.setText("");
        delivery2c.setText("");
        delivery3.setText("");
        delivery3b.setText("");
        delivery3c.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void petrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petrolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatePetrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatePetrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatePetrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatePetrol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatePetrol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delivery1;
    private javax.swing.JTextField delivery1b;
    private javax.swing.JTextField delivery1c;
    private javax.swing.JTextField delivery2;
    private javax.swing.JTextField delivery2b;
    private javax.swing.JTextField delivery2c;
    private javax.swing.JTextField delivery3;
    private javax.swing.JTextField delivery3b;
    private javax.swing.JTextField delivery3c;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField petrol;
    // End of variables declaration//GEN-END:variables
}
