/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addstaffs;


/**
 *
 * @author tzeletan
 */
public class generateReport extends javax.swing.JFrame {

    /**
     * Creates new form generateReport
     */
    public generateReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblReport = new java.awt.Label();
        JComboBox = new javax.swing.JComboBox<String>();
        jbtnGenerate = new java.awt.Button();
        jtaList = new java.awt.TextArea();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblReport.setText("Select Report :");

        JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly Sales Report"}));
        JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxActionPerformed(evt);
            }
        });

        jbtnGenerate.setLabel("Generate");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 207, Short.MAX_VALUE)
                            .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jtaList, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblReport, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(JComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtaList, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
if("January".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("DAILY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  +"O001                S001        11/1/2017          RM50.00\n" 
                  +"O002                S001        11/1/2017          RM20.00");
        }
else if("February".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("MONTHLY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  + "O001                S001        1/2/2017          RM50.00\n" 
                  + "O002                S001        11/2/2017          RM20.00");
        }
else if("March".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("MONTHLY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  + "O001                S001        1/3/2017          RM50.00\n" 
                  + "O002                S001        11/3/2017          RM20.00");
        }
else if("April".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("MONTHLY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  + "O001                S001        1/4/2017          RM50.00\n" 
                  + "O002                S001        11/4/2017          RM20.00");
        }
else if("May".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("MONTHLY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  + "O001                S001        1/5/2017          RM50.00\n" 
                  + "O002                S001        11/5/2017          RM20.00");
        }
else if("December".equals(jComboBox1.getSelectedItem()))
        {
                  jtaList.setText("MONTHLY SALES REPORT \n" + "Order ID        Staff ID        Order Date        Total Price\n"
                  + "O001                S001        1/12/2017          RM50.00\n" 
                  + "O002                S001        11/12/2017          RM20.00");
        }
            }//GEN-LAST:event_jbtnGenerateActionPerformed

    private void JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxActionPerformed

    }//GEN-LAST:event_JComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBox;
    private javax.swing.JComboBox jComboBox1;
    private java.awt.Button jbtnGenerate;
    private java.awt.Label jlblReport;
    private java.awt.TextArea jtaList;
    // End of variables declaration//GEN-END:variables
}
