/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import adt.ArrayQueue;
import adt.ArrayStack;
import adt.LList;
import adt.ListInterface;
import adt.QueueInterface;
import adt.StackInterface; 
import entity.DeliveryMan;
import entity.Job;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AssignDelivery extends javax.swing.JFrame {
        
    private ListInterface<DeliveryMan> deliveryList = new LList<>();
    private ListInterface<Job> jobList = new LList<>();
    /**
     * Creates new form AssignDelivery
     */
    public AssignDelivery() {
        initComponents();
        
        String[] orderID = {"O001","O002","O003","O004","O005"};
        String[] location = {"Wangsa Maju","Genting Klang","TBR","Wangsa Maju","TBR"};
        String[] jStatus = {"Assigned","Assigned","Pending","Delivered","Pending"};
        String[] staffID = {"S001","S002","S003","S004","S005"};
        String[] sStatus = {"Available","On Delivery","On Delivery","Available","Break"};
        String[] jobAssigned = {"0","1","3","0","0"};
        
        for(int i = 0; i<5; i++){
            DeliveryMan deliveryMan = new DeliveryMan(staffID[i], sStatus[i], jobAssigned[i]);
            Job job = new Job(orderID[i], location[i], jStatus[i]);
            
            deliveryList.add(deliveryMan);
            jobList.add(job);
        }
        
        jta1.setText("Job List \n" + jobList);
        jta2.setText("Delivery Man List \n" + deliveryList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtfJob = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDman = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJobActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Assign Delivery Job");

        jButton2.setText("Cancel");

        jLabel3.setText("ID of delivery man to assign job to : ");

        jLabel1.setText("ID of job to be assigned :");

        jta1.setColumns(20);
        jta1.setRows(5);
        jScrollPane1.setViewportView(jta1);

        jta2.setColumns(20);
        jta2.setRows(5);
        jScrollPane2.setViewportView(jta2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(714, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)
                                .addComponent(jtfJob, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfDman, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String job = jtfJob.getText();
        String man = jtfDman.getText();
        int firstCheck = 0;
        int secondCheck = 0;
        int confirmJob =0, confirmStaff =0;
               
        for(int a=1; a<=jobList.getNumberOfEntries();a++){
            if(jobList.getEntry(a).getOrderID().equals(job)){
                firstCheck++;
                confirmJob = a;
            }      
        }
        
        for(int e=1; e<=deliveryList.getNumberOfEntries();e++){
            if(deliveryList.getEntry(e).getStaffID().equals(man)){
                secondCheck++;
                confirmStaff = e;
            }      
        }
        
        
        if(firstCheck==1 && secondCheck==1){
            if(jobList.getEntry(confirmJob).getStatus().equals("Pending")){
                if(deliveryList.getEntry(confirmStaff).getStatus().equals("Break")){
                    JOptionPane.showMessageDialog(null, "Delivery man is on break.");
                }
                else{
                    if(deliveryList.getEntry(confirmStaff).getJobAssigned().equals("3")){
                        JOptionPane.showMessageDialog(null, "Delivery man's job already reached maximum(3).");
                    }
                    else{
                        int jobNum = Integer.parseInt(deliveryList.getEntry(confirmStaff).getJobAssigned());
                        jobNum++;
                        jobList.getEntry(confirmJob).setStatus("Assigned");
                        deliveryList.getEntry(confirmStaff).setStatus("On Delivery");
                        deliveryList.getEntry(confirmStaff).setJobAssigned(Integer.toString(jobNum));
                        jta1.setText("Job List \n" + jobList);
                        jta2.setText("Delivery Man List \n" + deliveryList);
                        JOptionPane.showMessageDialog(null, "Successfully assigned job!");
                    }
                }      
            }
            else{
                JOptionPane.showMessageDialog(null, "Job had been assigned or delivered.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong Job ID or Delivery Man ID.");
        }
        

        
        /*for(int a = 1; a < jobList.getNumberOfEntries() ; a++){
            if(jobList.getEntry(a).getOrderID().equals(job)){
                if(jobList.getEntry(a).getStatus().equals("Pending")){
                    for(int u = 1; u < deliveryList.getNumberOfEntries() ; u++){
                        if(deliveryList.getEntry(u).getStaffID().equals(man)){
                            if(deliveryList.getEntry(u).getStatus().equals("Break"))
                                JOptionPane.showMessageDialog(null, "Delivery Man on break...");
                            else{
                                if(deliveryList.getEntry(u).getJobAssigned().equals("3"))
                                    JOptionPane.showMessageDialog(null, "Delivery man's job already reached maximum(3).");
                                else{
                                    int jobNum = Integer.parseInt(deliveryList.getEntry(u).getJobAssigned());
                                    jobNum++;
                                    jobList.getEntry(a).setStatus("Assigned");
                                    deliveryList.getEntry(u).setStatus("On Delivery");
                                    deliveryList.getEntry(u).setJobAssigned(Integer.toString(jobNum));
                                    jta1.setText("Job List \n" + jobList);
                                    jta2.setText("Delivery Man List \n" + deliveryList);
                                    JOptionPane.showMessageDialog(null, "Successfully assigned job!");                                
                                }
                            }
                        }
                    }
                }
            }
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignDelivery().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jta1;
    private javax.swing.JTextArea jta2;
    private javax.swing.JTextField jtfDman;
    private javax.swing.JTextField jtfJob;
    // End of variables declaration//GEN-END:variables
}
